# This is a basic workflow to help you get started with Actions

name: CD/CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "publish"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    
    - uses: na-wu/vsce-publish-action@master
      with:
        args: "publish -p $VSCE_TOKEN"
      env:
        VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}

    # # Runs a single command using the runners shell
    # - name: Run a one-line script
    #   run: echo Hello, world!
    #     with:
    #       args: "publish -p $VSCE_TOKEN"
    #     env:
    #       VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
